### PR TITLE
Fixes issue with negative longitudes, by only using positive ones. As…

### PR DESCRIPTION
**Pull request by james-lan**
… per the OnStep mailing list.

### CODE REVIEW

**Comment by azwing** [comment]
Hi James,

seems you are much better than me in programming and using github, i am really a dummie in both.
I don't kow which way to solve the issue is the best, yours or mine.

I found the problem in lx200driver at function setSiteLongitude
so I cretate an LX200_OnStep::setSiteLongitude where I changed the formating (%.03d instead of %03d)
    snprintf(read_buffer, sizeof(read_buffer), ":Sg%.03d:%02d#", d, m);
and it works

On the other hand I am new to git also and have no idea how to include your pull request.
Can you help me on this side?

**Comment by james-lan** [comment]
https://help.github.com/articles/merging-a-pull-request/ 

There are a couple of methods, but assuming, that code hasn't been changed, the merge pull request would be the easiest.

**Comment by azwing** [comment]
James,

I tested your code but still someything does not work:

When I enter a location for example Brestwhich is -4 29 59.00
Kstars ends  355:30:01
so with your calculation
onstep_long = 360-longitude => 4,5
so I end up with :Sg004:30:00# which is East, not West

Maybe I am still wrong but when I use my code
    double onstep_long = longitude;
    if (onstep_long < -180)
        onstep_long += 360;
    if (onstep_long > 180)
        onstep_long -= 360;
and patched function
int LX200_OnStep::setSiteLongitude(int fd, double Long)
{
    //DEBUGFDEVICE(lx200Name, DBG_SCOPE, "<%s>", __FUNCTION__);
    int d, m, s;
    char read_buffer[32];

    getSexComponents(Long, &d, &m, &s);

    snprintf(read_buffer, sizeof(read_buffer), ":Sg%.03d:%02d#", d, m);

    return (setStandardProcedure(fd, read_buffer));
}
I send always the correct command ,
either :Sg-ddd:mm:ss# or :Sgddd:mm:ss#
and it works apparentlly

**Comment by Blueshawk** [comment]
Hi James, thanks for helping! 
 Looks like both may be needed. I agree that a full flip of the coords may work because the OnStep phone app reacts as expected if fed -80 or +80, but trying to enter anything negative (-80) from indi control panel results in error, and +80 shows on the map as east of prime meridian instead of west. --hence confusion between the two. recent pulls have converted -80 to 279 which looks wrong but works in app, but fails if downloaded to mount, which is the only option in Kstars indi that works, the upload from mount function results in the target error in the starmap and below Horizon limit stops.
I'll have my mount in the shop all weekend due to rain but should be able to run simulations as needed, and as time allows.
clear skies!? what'r those!

**Comment by james-lan** [comment]
The flip (360-longitude) needs to be done to be correct for OnStep using LX200 style

I tested with my code, and found that it worked great, I even got correct median flips! (First time that's worked, yay!) 

"so I end up with :Sg004:30:00# which is East, not West " That's actually West for the mount protocol. 

The reason is that **West is positive, East is negative for LX200 type mounts** (Which is absolutely _backwards_ from normal INDI's (and just about _everything_ else's) handling of longitudes that doesn't use W or E to be explicit.) 

From command.ino in OnStep (This is the important one, if this were different, LX200 protocol be damned):
//  :SgsDDD*MM# or :SgDDD*MM#
//          Set current sites longitude to sDDD*MM an ASCII position string, East longitudes can be as negative or >180 degrees
//          Return: 0 on failure
//                  1 on success
...
//  :Gg#   Get Current Site Longitude
//         Returns: sDDD*MM#
//         The current site Longitude. East Longitudes are negative

OnStep is consistent with LX200 From Meade's LX200 https://www.meade.com/support/LX200CommandSet.pdf : 
_:Gg# 
Get Current Site Longitude 
Returns: sDDD*MM# 
The current site Longitude. East Longitudes are expressed as negative_  


_:SgDDD*MM# 
Set current site’s longitude to DDD*MM an ASCII position string 
 Returns: 
0 – Invalid 
1 - Valid_ 

(Note the documentation on Meade's set function doesn't mention E vs W, but every other piece of documentation on lx200 I can find agrees, East is negative/West is positive. That includes in INDI the lx200generic.cpp's Update Location function: _if (!isSimulation() && setSiteLongitude(PortFD, 360.0 - longitude) < 0)_ ) 

For values seen in INDI, do note that the get function LX200Generic::sendScopeLocation(), compensates for this: (dd being degrees, mm minutes) My comments in []
        if (dd > 0) [So What the mount thinks is West (+)]
            LocationNP.np[1].value = 360.0 - (dd + mm / 60.0); [Flip using 360 degrees]
        else [What the mount thinks is East (-) ] 
            LocationNP.np[1].value = (dd - mm / 60.0) * -1.0; [Flip just multiplying by -1]

Example from my log: ```

[2018-02-08T04:20:50.436 CST DEBG ][           org.kde.kstars.indi] - LX200 OnStep : "[SCOPE] <getSiteLongitude> "
[2018-02-08T04:20:50.436 CST DEBG ][           org.kde.kstars.indi] - LX200 OnStep : "[SCOPE] CMD <:Gg#> "
[2018-02-08T04:20:50.436 CST DEBG ][           org.kde.kstars.indi] - LX200 OnStep : "[SCOPE] RES <+097*20> "
[2018-02-08T04:20:50.436 CST DEBG ][           org.kde.kstars.indi] - LX200 OnStep : "[SCOPE] VAL [97,20] "
[2018-02-08T04:20:50.436 CST DEBG ][           org.kde.kstars.indi] - LX200 OnStep : "[DEBUG] Mount Controller Latitude: 37.6833 Longitude: 262.667 "

```

**Pull request merged**
